import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [data, setData] = useState(null);

  // useEffect(() => {
  //   const fetchData = async() => {
  //     const response = await fetch("/api/open-close");
  //     const data = await response.json();
  //     setData(data);
  //   }
  //   fetchData();
  // }, [])

  return (
    <>
      <Head>
        <title>Trade To Learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        {/* {
          data ?
            <table>
              <thead>
                <tr>
                  <th>Ticker</th>
                  <th>Close Price</th>
                  <th>Highest Price</th>
                  <th>Lowest Price</th>
                  <th>Open Price</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{data["symbol"]}</td>
                  <td>{data["close"]}</td>
                  <td>{data["high"]}</td>
                  <td>{data["low"]}</td>
                  <td>{data["open"]}</td>
                </tr>
              </tbody>
            </table> : <div>Loading...</div> 
        } */}
      </section>
    </>
  );
}
